# Generated by Django 2.2.3 on 2019-08-20 12:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='博客分类')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
                'db_table': 'blog_category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='博客标签')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '博客标签',
                'verbose_name_plural': '博客标签',
                'db_table': 'blog_tag',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='博客标题')),
                ('body', ckeditor.fields.RichTextField(verbose_name='博客内容')),
                ('summary', models.CharField(blank=True, max_length=256, verbose_name='博客摘要')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='最后修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='博客作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory', verbose_name='博客分类')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='blog.BlogTag', verbose_name='博客标签')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'db_table': 'blog_article',
                'ordering': ['id'],
            },
        ),
    ]
