# Generated by Django 2.2.3 on 2019-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.BlogTag', verbose_name='博客标签'),
        ),
    ]
