# Generated by Django 2.2.4 on 2019-08-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190820_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
