# Generated by Django 2.2.4 on 2019-08-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='pic',
            field=models.ImageField(blank=True, upload_to='blog/<django.db.models.fields.CharField>/'),
        ),
    ]
