# Generated by Django 2.2.4 on 2019-08-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogarticle_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='pic',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='picture',
            field=models.ImageField(blank=True, upload_to='blog/'),
        ),
    ]
