# Generated by Django 2.2.3 on 2019-08-20 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='电话')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='城市')),
                ('avatar', models.ImageField(blank=True, upload_to='image/%Y%m%d/', verbose_name='邮箱')),
                ('profile', models.TextField(blank=True, max_length=500, verbose_name='简介')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'userinfo',
                'ordering': ['-created_time'],
            },
        ),
    ]
