# Generated by Django 2.2.4 on 2019-08-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, upload_to='image/%Y%m%d/', verbose_name='头像'),
        ),
    ]
